### ISSUE TITLE
with-sdk.md Warning block escapes hyperlink markdown

### ISSUE THREAD

**Issue by jpan-box** [box/developer.box.com#100]
The "User types" hyperlink markdown appears to be escaped on this guide:
https://developer.box.com/guides/authentication/jwt/with-sdk/

![Screen Shot 2020-03-09 at 11 02 02 AM](https://user-images.githubusercontent.com/37150601/76227908-60acae00-61f6-11ea-9b1b-582b41dd886d.png)

I took a look at the .md file and nothing seems egregious, so I'm not sure why it's being escaped. If there's an easy fix, I'm happy to put up the PR!

```
<Message warning>
  # Service Accounts

  At this point the application is authenticated as an application user, not as
  a managed or app user. Head over to our guide on [User
  Types][g://authentication/user-types] to learn more about the different types
  of users.
</Message>

**Comment by cbetta** [comment]
Thanks for reporting, fixed by adding some newlines, for now. https://github.com/box/developer.box.com/commit/4495326cb49a774ad07ebe6d96567b31b996eec6
