### ISSUE TITLE
Gap?

### ISSUE THREAD

**Issue by Sunyang730** [box/developer.box.com#2]
<img width="327" alt="Screen Shot 2019-05-06 at 12 52 39 PM" src="https://user-images.githubusercontent.com/6230982/57252444-f8eb6c80-7000-11e9-8ba6-784c4e0aa094.png">

Are these gaps expected on the examples?

**Comment by cbetta** [comment]
Hmm. What browser is that in?

**Comment by cbetta** [comment]
This has been resolved by adding a subtle border.
