### ISSUE TITLE
Directory to Box drive is an empty symlink

### ISSUE THREAD

**Issue by daria-rogova** [box/developer.box.com#231]
I'm sorry if it is not a right place for the issue.

Some of our customers use Box drive to store data. So we need to work with paths to Box drive. We use c++ boost filesystem library to process paths. The boost library considers path to Box: C:\Users\User\Box as an empty symlink, which is wrong. So we unable to work work with paths to Box.

Could there be any workaround or changes from your side?
We've already filled an issue to boost on github:
https://github.com/boostorg/filesystem/issues/187.

Unfortunately there is no inclination for the issue to be fixed from the boost side.
Could it be some advice from your side?

**Comment by knmeiss** [comment]
Daria - This repository is specific to developer.box.com and Box developer documentation. I do see you posted this in our [Support Forums](https://support.box.com/hc/en-us/community/posts/1500001146222-Directory-to-Box-drive-is-an-empty-symlink-), which is going to be the best place for a question of this nature.

**Comment by daria-rogova** [comment]
@knmeiss thank you!
