### ISSUE TITLE
media download using MediaLibrary contain same name for all media.

### ISSUE THREAD

**Issue by bbashel1** [box/developer.box.com#8]
When I download a media using box responded URL then a downloaded file gets download with the filename. If MediaLibrary process the same URL them it contains as download.png/jpeg. Is there any to send encoded filename along with media URL?

**Comment by cbetta** [comment]
Hey @bbashel1 I am not too sure I follow. I'd recommend heading over to our developer forum and ask the question there again.

https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
