### ISSUE TITLE
Minor style issue with sub-bullets

### ISSUE THREAD

**Issue by PJSimon** [box/developer.box.com#81]
On this page:
https://developer.box.com/en/guides/api-calls/permissions-and-errors/rate-limits/
there are four bullets under Search.
<img width="502" alt="Screen Shot 2020-01-15 at 9 58 27 PM" src="https://user-images.githubusercontent.com/12190288/72497758-42bc6180-37e2-11ea-883a-637f8e71f6fe.png">

But on this page:
https://github.com/box/developer.box.com/blob/master/content/guides/api-calls/permissions-and-errors/rate-limits.md
it appears the there should be two main bullets, with the third and fourth being sub-bullets.
<img width="630" alt="Screen Shot 2020-01-15 at 9 58 16 PM" src="https://user-images.githubusercontent.com/12190288/72497766-47811580-37e2-11ea-81fc-aaeabc05ed87.png">

I didn't know what changes to make to the MD file to get the rendering to change, so I'm submitting it as an issue.

**Comment by cbetta** [comment]
So it seems that most markdown parsers don't support double nested lists. Learned something new. I've rewritten the content without the second nesting.
